# Generated by Django 5.2.7 on 2025-10-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="آدرس ایمیل معتبر کاربر",
                        max_length=255,
                        unique=True,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام و نام خانوادگی کاربر",
                        max_length=100,
                        verbose_name="نام کامل",
                    ),
                ),
                (
                    "remember_me",
                    models.BooleanField(
                        default=False,
                        help_text="در صورت فعال بودن، نشست کاربر حفظ می\u200cشود",
                        verbose_name="مرا به خاطر بسپار",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا حساب کاربری فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="آیا کاربر دسترسی مدیریتی دارد؟",
                        verbose_name="مدیر",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="توضیح کوتاه درباره کاربر",
                        verbose_name="بیوگرافی",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="آپلود تصویر پروفایل",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="شماره موبایل کاربر",
                        max_length=15,
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="تاریخ تولد کاربر",
                        null=True,
                        verbose_name="تاریخ تولد",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "مرد"), ("F", "زن"), ("O", "سایر")],
                        help_text="انتخاب جنسیت",
                        max_length=1,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="آدرس وب\u200cسایت یا شبکه اجتماعی",
                        verbose_name="وب\u200cسایت شخصی",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="شهر یا کشور",
                        max_length=100,
                        verbose_name="محل سکونت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل",
                "verbose_name_plural": "پروفایل\u200cها",
            },
        ),
    ]
